const GET_USER_SUCCESS="GET_USER_SUCCESS";

const ADD_USER_SUCCESS="ADD_USER_SUCCESS";

const EDIT_USER_SUCCESS="EDIT_USER_SUCCESS";

const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS";

export{
    GET_USER_SUCCESS,
    DELETE_USER_SUCCESS,
    EDIT_USER_SUCCESS,
    ADD_USER_SUCCESS
}
