export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const SET_PRODUCTS_ROUTE = "SET_PRODUCTS_ROUTE";
export const SET_ALL_PRODUCTS_DATA = "SET_ALL_PRODUCTS_DATA";


export const SET_SINGLE_PRODUCT_DATA = "SET_SINGLE_PRODUCT_DATA";


export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCTS_SUCCESS";
